- name: Install requirements
  become: yes
  become_user: root
  become_method: sudo
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - gpg
    state: present

- name: Install npm
  become: true
  ansible.builtin.package:
    name:
      - npm
    state: latest
    update_cache: yes

- name: Install nodejs
  ansible.builtin.shell: |
    curl -SLO https://deb.nodesource.com/nsolid_setup_deb.sh
    chmod 500 nsolid_setup_deb.sh
    ./nsolid_setup_deb.sh 16
    apt-get install nodejs -y

- name: Install http-server globally.
  community.general.npm:
    name: http-server
    global: true

- name: Set capabilities for http-server
  ansible.builtin.shell:  setcap CAP_NET_BIND_SERVICE=+eip /usr/bin/node

#Я четсно пытался ¯\_(ツ)_/¯
#- name: Add keyrings directory
#  become: yes
#  become_user: root
#  become_method: sudo
#  file:
#    path: /etc/apt/keyrings
#    state: directory
#    mode: 0755

#- name: Add nodejs apt key
#  become: yes
#  become_user: root
#  become_method: sudo
#  apt_key:
#    url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"
#    state: present

#- name: Add nodejs 16.x ppa for apt repo
#  become: yes
#  become_user: root
#  become_method: sudo
#  apt_repository:
#    repo: "deb https://deb.nodesource.com/node_16.x nodistro main"
#    state: present
#    update_cache: yes

#- name: Install nodejs
#  become: yes
#  become_user: root
#  become_method: sudo
#  apt:
#    update_cache: yes
#    name: nodejs
#   state: present

- name: Add www-data user
  become: yes
  become_user: root
  become_method: sudo
  user:
    name: "www-data"
    create_home: no
    shell: /sbin/nologin

- name: Create directory
  become: yes
  become_user: root
  become_method: sudo
  file:
    path: /var/www-data
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Download artifact from Nexus using curl
  ansible.builtin.get_url:
    url: "https://nexus.k8s.praktikum-services.tech/repository/std-022-039-frontend/std-022-039-frontend/{{ frontend_npm_version }}/sausage-store-{{ frontend_npm_version }}.tar.gz"
    username: "{{ student_var  }}"
    password: "{{ nexus_password  }}"
    dest: "/tmp/sausage-store.tar.gz"

- name: Untar artifact
  become: yes
  become_user: root
  become_method: sudo
  ansible.builtin.unarchive:
    src: /tmp/sausage-store.tar.gz
    dest: /var/www-data
    owner: www-data
    group: www-data
    remote_src: yes

- name: Jinja template configuration for frontend-service
  become: yes
  become_user: root
  become_method: sudo
  template:
    src: ../templates/sausage-store-frontend.service.j2
    dest: /etc/systemd/system/sausage-store-frontend.service

- name: Reading configuration systemd
  become: yes
  become_user: root
  become_method: sudo
  systemd:
   daemon_reload: yes

- name: Deploy
  become: yes
  become_user: root
  become_method: sudo
  service:
    name: sausage-store-frontend
    state: started
