variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - deploy

deploy-kubernetes-helm:
  stage: build
  image: alpine/helm
  script:
    - helm package ./sausage-store-chart --version ${VERSION}
  artifacts:
    paths:
      - ./sausage-store-${VERSION}.tgz
    expire_in: 1 week

save-in-repo-kubernetes-helm:
  stage: deploy
  image: alpine/helm
  before_script:
    - apk add curl
  script:
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} ${NEXUS_REPO_URL_HELM} --upload-file ./sausage-store-${VERSION}.tgz
