---
apiVersion: v1
kind: Service
metadata:
   name: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: frontend
