---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmdIaVIzUzJjbXdwdU1uamwwYzBGN3Z6SA==
type: Opaque

---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOnsidXNlcm5hbWUiOiJzdGQtMDIyLTAzOSIsInBhc3N3b3JkIjoiZHhNNDF1NVgiLCJlbWFpbCI6InN0ZC0wMjItMDM5IiwiYXV0aCI6ImMzUmtMVEF5TWkwd016azZaSGhOTkRGMU5WZz0ifX19
kind: Secret
metadata:
  creationTimestamp: "2024-02-19T17:46:54Z"
  name: regcred
  namespace: std-022-039
  resourceVersion: "1377366609"
  uid: 9490914e-6fa8-4538-9e9c-a09b5a5d651c
type: kubernetes.io/dockerconfigjson