---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: aHZzLmdIaVIzUzJjbXdwdU1uamwwYzBGN3Z6SA==
type: Opaque
---
apiVersion: v1
data:
  .dockerconfigjson: ewogICAgICAgICJhdXRocyI6IHsKICAgICAgICAgICAgICAgICJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1OjUwNTAiOiB7CiAgICAgICAgICAgICAgICAgICAgICAgICJhdXRoIjogImMzUmtMVEF5TWkwd016azZaSGhOTkRGMU5WZz0iCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9
kind: Secret
metadata:
  creationTimestamp: "2024-02-19T18:02:37Z"
  name: docker-config-secret
  namespace: std-022-039
  resourceVersion: "1377391781"
  uid: 3c0b1053-d9cc-4286-9c18-6ed44218d98d
type: kubernetes.io/dockerconfigjson